### ISSUE TITLE
Defaults are not working

### ISSUE THREAD

**Issue by claudiu-cristea** [drush-ops/drush#1307]
I'm using the latest from master. Here's my make file that fails because of `defaults:`:

```yaml
core: 7.x
api: 2

defaults:
  projects:
    download:
      type: file

projects:
  drupal:
    download:
      url: ../.resource/make/vendor/drupal/drupal-7.35.tar.gz
```
If I move the `type: file` under `drupal[download]` works well.

I don't know if it's a bug or the docs are not clear for me https://github.com/drush-ops/drush/blob/master/docs/make.md#defaults.
