### ISSUE TITLE
drush make working-copy option downloads wrong version.

### ISSUE THREAD

**Issue by JorisVanEijden** [drush-ops/drush#1396]
This makefile:

``` yaml
core: "7.x"
projects:
  drupal:
    type: "core"
    version: "7.x"
    download:
      working-copy: true
```

Will download drupal 8.0.1  :open_mouth:

 I know I can work around it by adding a `branch: 7.x` but that doesn't make it less of a WTF.

Maybe make `branch` required when `working-copy` is enabled?
