### ISSUE TITLE
Projects without any "values" are not installed by drush make

### ISSUE THREAD

**Issue by pingers** [drush-ops/drush#1473]
make.utilities.inc line 236 make_validate_info_file():
`$info['projects'] = array_filter($info['projects']);`
I tried specifying a module without any values underneath, which should be filled in by the defaults. However, array_filter() is too aggressive and removes these modules. FALSE is the case array_filter() is designed to handle, but also doesn't play nice when there's no other values specified. I tried an empty array too, but no luck. The example below should download panels and views, but not context module.

Perhaps we need a callback for array_filter() which doesn't strip out the keys before defaults get applied?

example.make.yml

```
projects:
  panels:
  views: []
  context: FALSE
defaults:
  type: module
  subdir: contrib
```
