### ISSUE TITLE
YAML file recognised as INI

### ISSUE THREAD

**Issue by thewilkybarkid** [drush-ops/drush#1479]
The following YAML Make file is recognised as an INI:

``` yaml
api: 2
core: '7.x'

projects:
  date_facets:
    version: '1.0-beta2'
    patch:
      - 'http://cgit.drupalcode.org/date_facets/patch/?id=17b2758128b201fcc83100df9da6a1f8160be836'
```

The equals sign inside the patch URL is the trigger.
