### ISSUE TITLE
make includes in distro.make.yml are not processed.

### ISSUE THREAD

**Issue by mfrieling** [drush-ops/drush#1568]
I have a `distro-dev.make.yml` together with some bash script in a seperate Git repo called bootstrap and the `profile.make.yml` in the profile repo. They mostly look like in the [drush make documentation](https://github.com/drush-ops/drush/blob/master/docs/make.md#user-content-recursion) with one main exception. In bootstrap I have different make file for dev and release: `distro-dev.make.yml` and `distro-release.make.yml`, the difference is that _distro-dev_ clone the profile from the dev branch and _distro-release_ from a version tag and specifies the `full_version`.

As I have some custom modules in separate repos with make files and want to do the same dev/release building and versioning there I cannot include my profile as project in the distro. That dos not support selection of the makefile to use. Therefor I included the `profile-dev.make.yml` / `profile-release.make.yml` from the repository as in https://github.com/drush-ops/drush/blob/master/docs/make.md#includes.
### Make files

**distro-dev.make.yml**

``` yml
api: 2
core: 7.x

defaults:
  projects:
    subdir: contrib

projects:
  drupal:
    type: core
    version: 7.39
    patch:
      # Use new lines in plain text format: http://drupal.org/node/1152216
      - http://drupal.org/files/text-plain-1152216-24.patch

includes:
  my_profile:
    makefile: my_profile-dev.make.yml
    download:
      type: git
      url: # valid git url
      branch: dev
```

**distro-release.make.yml** (just the _includes_ part, the rest is identical to `distro-dev.make.yml`)

``` yml
includes:
  my_profile:
    makefile: my_profile-release.make.yml
    download:
      type: git
      url: # valid git url
      branch: master
      tag: 7.x-1.1
      full_version: 7.x-1.1
```

**my_profile-dev.make.yml**

``` yml
api: 2
core: 7.x

projects:
  my_project_1:
    type: module
    subdir: features
    download:
      type: git
      url: # valid git url
      branch: 7.x-2.x
  my_project_2:
    # similar to my_project_1

  ctools:
    version: ~
  # other contrib modules
```

**my_profile-release.make.yml** (just the part with differences)

``` yml
projects:
  my_project_1:
    type: module
    subdir: features
    download:
      type: git
      url: # valid git url
      branch: 7.x-2.x
      tag: 7.x-2.0
      full_version: 7.x-2.0
```
### Error Description

This setup should achieve my goal to build the custom modules from their dev branch for dev builds and from the master branch using a version tag and the full_version to write into the .info file on release builds like with the my_profile.info and all other .info file in the my_profile repo.

Actually Drush
- Clones the _my_profile_ repo and checks out the correct branch/tag
- Downloads Drupal Core 7.39
- Applies the specifiec patches to Drupal Core and generates the PATCHES.txt file
- **Finishes with _Command dispatch complete_**

The `my_profile-dev.amke.yml` is not processed.
Another thing to note is that the _includes_ section of the `distro-dev.make.yml` gets processed before the Drupal Core is downloaded, thus before the _projects_ section is processed. If I add the _my_profile_ as project everything works fine but I cannot specify which of it's make files should be processed.
### Alternative not working as well

**[Overriding properties](https://github.com/drush-ops/drush/blob/master/docs/make.md#overriding-properties) does not work as well**, at least not in YAML syntax. I haven't tested it with INI syntax. (My first idea was to setup the profile and custom module make files for dev builds and overwrite the branch, tag and fuil_version information in the `distro-release.make.yml`. But then it says that it is not a valid type. Maybe because it is parsed before the included make file containing the base information is loaded and parsed.
