### ISSUE TITLE
make-update updates core from 7.x to 8.x.x

### ISSUE THREAD

**Issue by kazdegroot** [drush-ops/drush#1842]
Given the following .make.yml file
```yml
core: 7.x
api: 2
defaults:
  projects:
    subdir: contrib
    translations:
      - nl
projects:
  drupal:
    version: '7.41'
    type: core
  features:
    version: '2.7'
  strongarm:
    version: '2.0'
```

running `drush make-update makefile.make.yml` produces:

```yml
core: 7.x
api: 2
defaults:
  projects:
    subdir: contrib
    translations:
      - nl
projects:
  drupal:
    version: 8.0.1
    type: core
  features:
    version: 8.x-3.0-alpha5
  strongarm:
    version: '2.0'
```

While I guess there is a point to be made that it really does attempt to update everything to the latest version, I imagine that this function shouldn't suggest core updates.
