### ISSUE TITLE
make-generate throws warnings and adds irrelevant entries for certain D8 themes

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#2028]
See: https://travis-ci.org/drush-ops/drush/builds/111663516

In Drupal 7 sites, `make-generate` works as expected:

```
root@drush:~/tmp# drush dl drupal-7; cd drupal-7.43; drush -y site-install --db-url=$UNISH_DB_URL/site7; drush dl omega; drush -y en omega
[...]
root@drush:~/tmp/drupal-7.43# drush make-generate
core: 7.x
api: 2
projects:
  drupal:
    version: '7.43'
  omega:
    version: '4.4'
```

In Drupal8 sites, however, it throws warnings and adds some odd entries to the makefile:

```
[...]
root@drush:~/tmp/drupal-8.0.4# drush make-generate
The following module is missing from the file system: omega_starterkit bootstrap.inc:231                                   [warning]
Unknown path for omega_starterkit module.                                                                                  [warning]
The following module is missing from the file system: omega_simple_starterkit bootstrap.inc:231                            [warning]
Unknown path for omega_simple_starterkit module.                                                                           [warning]
The following module is missing from the file system: omega bootstrap.inc:231                                              [warning]
Unknown path for omega module.                                                                                             [warning]
core: 8.x
api: 2
projects:
  drupal:
    version: 8.0.4
  omega:
    type: module
    custom_download: true
    version: 5.0-alpha5

```

I believe that this is due to Omega (a theme) shipping with some modules, which is a bit of an edge case. The warnings are being emitted from Drupal core's bootstrap.inc, not Drush's.

After discussion with @weitzman, I'm going to change our tests to use a more standard module, until we can get this worked out.
