### ISSUE TITLE
make-convert does not quote versions with metadata extensions

### ISSUE THREAD

**Issue by komlenic** [drush-ops/drush#2404]
Any version numbers that include metadata extensions are not quoted in the resulting make.yml file produced from `drush make-convert`.

Example:

```
projects[field_collection_table] = "1.0-beta3"
projects[entityreference] = "1.1"
```

...becomes:

```
  field_collection_table:
    version: 1.0-beta3
  entityreference:
    version: '1.1'
```

Note that 1.0-beta3 is produced unquoted.
