### ISSUE TITLE
Working with fixed revisions in Drupal 8

### ISSUE THREAD

**Issue by mpastas** [drush-ops/drush#2472]
Currently our project is experimenting that drush make is not handling the **revision** key given in the YML. We noticed it since the patches are not applying after code releases.

i.e.
```
cshs:
    version: "1.x-dev"
    subdir: "contrib"
    revision: "5c21e7e"
    patch:
      - "https://www.drupal.org/files/issues/fix-localized-constant-2774919-11.patch"
```

**Comment by mpastas** [comment]
I realized the right sintax should be:

```
cshs:
    subdir: "contrib"
    download:
      revision: "3adc2d6"
    patch:
      - "https://www.drupal.org/files/issues/fix-localized-constant-2774919-5.patch"
```

**download** index is very important here.
