### ISSUE TITLE
drush make in yml format is not working for libraries of type get

### ISSUE THREAD

**Issue by MuschPusch** [drush-ops/drush#2653]
Executing a yaml makefile and a 'deprecated' format. Yaml format doesn't download and unzip's  libraries (drush 8.1.10)

The yaml makefile:
```drush make /var/www/drush.make --no-core   /var/www/public_html -vvv```

```
core: 7.x
api: 2
projects:
  views:
    version: "3.14"

libraries:
  underscore:
    destination: "libraries"
    download:
      - url: "https://github.com/jashkenas/underscore/archive/1.5.2.zip"
      - type: "get"
```

The 'deprecated' format info style format:

```drush make /var/www/test.make --no-core   /var/www/public_html -vvv```
```
api = 2
core = 7.x

projects[views] = 3.14

libraries[underscore][destination] = libraries
libraries[underscore][download][url] = https://github.com/jashkenas/underscore/archive/1.5.2.zip
libraries[underscore][download][type] = get
```
