### ISSUE TITLE
Unable to install Drupal if installation profile contains a reaction rule

### ISSUE THREAD

**Issue by EAnushan** [drush-ops/drush#2735]
I've created a custom installation profile for Drupal that contains configuration to create a reaction rule for the rules module. Reaction rules use Drupal 8's plugin API. If I install Drupal via the web UI (at `/core/install.php`), and select my custom installation profile, the installation completes successfully.

Unforunately, if I install Drupal using drush, and select my custom installation profile, the installation fails with the following exception:
`
Drupal\Core\Field\FieldException: Attempt to create a field user_picture that does not exist on entity type user. in /var/www/html/web/core/modules/field/src/Entity/FieldConfig.php:286
`

Reproduction Steps:

1. Create a custom installation profile (or modify the standard one).
2. Depend on rules in your `custom_profile.info.yml` file. You will need to run `composer require drupal/rules "dev-3.x as 3.0"` to depend on the latest version of rules, or download the tar manually.
3. Add a `rules.reaction.custom_rule.yml` file under your installation profiles `config/install` directory.
4. Place the following YAML inside your `rules.reaction.custom_rule.yml` file:
```
langcode: en
status: true
dependencies: {  }
id: custom_rule
label: 'Custom Rule'
events:
  -
    event_name: rules_user_login
description: ''
tags:
  - ''
config_version: '3'
expression:
  id: rules_rule
  uuid: 3fb58cfe-0793-4fc5-8e17-8154ed8a7768
  conditions:
    id: rules_and
    uuid: 4e243d4c-3a05-432f-9a56-8df9014b8875
    conditions: {  }
  actions:
    id: rules_action_set
    uuid: 22d40352-6675-410b-93ce-0f4be7f4fcf5
    actions:
      -
        id: rules_action
        uuid: 6058b95d-2cce-4078-ae99-5865d648da40
        context_values:
          message: 'Custom Rule Message'
          type: status
          repeat: false
        context_mapping: {  }
        context_processors:
          message:
            rules_tokens: {  }
          type:
            rules_tokens: {  }
          repeat:
            rules_tokens: {  }
        provides_mapping: {  }
        action_id: rules_system_message
```
4. Run `cd ${DRUPAL_ROOT}/web && ../vendor/bin/drush site-install ${DRUPAL_PROFILE} -y --db-url="mysql://${DRUPAL_DB_USER}:${DRUPAL_DB_PASSWORD}@${DRUPAL_DB_HOST}/${DRUPAL_PROFILE}" --account-name="${DRUPAL_ACCOUNT_NAME}" --account-mail="${DRUPAL_ACCOUNT_MAIL}" --account-pass="${DRUPAL_ACCOUNT_PASS}" --site-mail="${DRUPAL_SITE_MAIL}" --site-name="${DRUPAL_SITE_NAME}"`
5. Site installation will fail with the exception above.

**A very important side note:** This ONLY happens if `sites/default/settings.php` doesn't exist or does exist, but doesn't contain any database configuration in the `$databases` array. If you prefill `settings.php` with a valid `$databases` array, the installation will proceed without error. Only when drush automatically copies `default.settings.php` to `settings.php` and generates the `$databases` array does the installation fail.
