### ISSUE TITLE
drush make-update updates modules to D8, even when core is set to 7.x

### ISSUE THREAD

**Issue by Jelle-S** [drush-ops/drush#2766]
After running `drush make-update build.make.yml --result-file=build.make.yml`

My make file looks like this:
```
core: 7.x
api: 2
defaults:
  projects:
    subdir: contrib
projects:
  drupal:
    version: 8.3.2
    type: core
[...]
```
So "core" is still set to "7.x" but Drupal core itself and all contrib modules are updated to 8.x
