### ISSUE TITLE
Shell aliases (or yml commands) for Drush 9

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#2943]
We should follow the lead of Travis CI and Circle CI & c. and put simple shell scripts in our yml configuration files:
```
shell:
  -
    command: hello
    option: who
    default: who World
    script:
      - echo "Hello, $WHO"
  -
    command: knock:knock
    script:
      - echo "Who's there?"
```
Environment variables are automatically set for each defined option and argument.

We could potentially have a shortcut for Drush commands, but I'm not sure that it is necessary.

**Comment by weitzman** [comment]
Look good to me, as long as we don't need much custom code to process the yaml file and execute the script. Perhaps there is code we can bring in.

**Comment by greg-1-anderson** [comment]
Or maybe:
```
shell:
  -
    command: hello
    options
      who: World
      count: 1
    option-descriptions:
      who: Who to say hello to
      count: How many times to say hello
    script:
      - seq $COUNT | xargs -Iz echo "Hello, $WHO"
```
The question is, is either of these forms significantly simpler than a php commandfile to make this worthwhile?
