### ISSUE TITLE
Cannot use boolean values in config

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2956]
For example, the following does have any effect as seen by the command callback not getting right value in $options.

```
command:
  image-flush:
      options:
        all: true
```
