### ISSUE TITLE
drush-script for Drush9

### ISSUE THREAD

**Issue by yobottehg** [drush-ops/drush#3017]
In one of our projects i updated to Drupal 8.4 and could not find a suitable set of dependencies using composer without updating to Drush9.

Now i'm sitting here and want to update the drush aliases. I looked on #3010 and added following to drush/project.alias.yml:

```
local:
  root: '/var/www/drupalvm/docroot'
  uri: 'www.project.dev'
  host: 'www.project.dev'
  user: 'vagrant'
  os: 'Linux'
  ssh:
    options: '-o PasswordAuthentication=no -i ~/.vagrant.d/insecure_private_key'
  paths:
    - drush: '/var/www/drupalvm/vendor/bin/drush'
    - drush-script: '/var/www/drupalvm/vendor/bin/drush'
```

The ssh connection seems to work but the remote side can't find drush. How should i set the pathes?

What is wrong and what do i need to adjust?

for `drush @project.dev cr` i get the following output:

```
bash: drush: command not found
Connection to www.project.dev closed.
```
