### ISSUE TITLE
Rename name.alias.yml to name.site.yml and drop support for group.aliases.yml

### ISSUE THREAD

**Issue by webflo** [drush-ops/drush#3107]
The docs (https://raw.githubusercontent.com/drush-ops/drush/master/examples/example.aliases.yml) have no example for a "aliases.yml". How should this fill look like? I tried the following.

```
stage:
  host: stage.example.com
prod:
  host: example.com
```

Does not work.

```
sites:
  stage:
    host: stage.example.com
  prod:
    host: example.com
```

Does not work.

```
sites:
  my_project:
    stage:
      host: stage.example.com
    prod:
      host: example.com
```

Works.

This means the resulting site-aliases are quite verbose. Because its always site+environment. I use this in combination with drupal-composer/drupal-project and never have global available site-aliases. Is it still possible to use short site aliases? example.aliases.yml has ``@stage`` as an example but i was not able to produce such an site-alias.

---

PS: I did some debugging. ``\Drush\SiteAlias\SiteAliasFileLoader::fetchAliasRecordFromSiteAliasData`` in \Drush\SiteAlias\SiteAliasFileLoader::fetchAliasRecordFromGroupAliasData returns ``false`` if the group is empty. It this the root cause? Thanks!
