### ISSUE TITLE
Site-specific drush.yml file not loaded

### ISSUE THREAD

**Issue by grasmash** [drush-ops/drush#3277]
Drush does not appear to load `docroot/sites/default/drush.yml`, although the documentation indicates that this should work.

Adding the following to `drush/drush.yml` has no effect:
```
drush:
  paths:
    config:
      - ../docroot/sites/default/drush.yml
```

Executing `drush status --config=docroot/sites/default/drush.yml` also does not load it.
