### ISSUE TITLE
Drush 9 output values return as string rather than array when executed on Ansible with remote alias

### ISSUE THREAD

**Issue by ericpugh** [drush-ops/drush#3298]
_Using Drush 9.0.0-rc2 and Ansible 2.4_
I'm having an issue executing drush commands from a simple Ansible playbook, and I'm thinking that there is something about Drush 9 return codes that are causing a problem.

For example, below is a simple playbook to test executing on a remote alias from a local DrupalVM inventory. All drush commands when executed directly on the local box with the remote alias work as expected. Also, non-drush tasks when executed from the Ansible playbook work as expected. However, drush commands always fails (stopping the playbook execution) even though the command successfully executes on the remote box.

Example playbook:
```
- hosts: all
  become: no

  tasks:
    - name: Execute a drush command on the remote.
      command: "/var/www/drupal/vendor/bin/drush @drupalvm.remote cr"
      args:
        chdir: "/var/www/drupal/web"
```
This fails, returning the following to the Ansible recap, but the cache _is_ sucessfully rebuilt on the remote :
```
fatal: [192.168.88.88]: FAILED! => {
	"changed": true, 
	"cmd": ["/var/www/drupal/vendor/bin/drush", "@drupalvm.remote", "cr"], 
	"delta": "0:00:23.032100", 
	"end": "2018-01-10 13:04:33.274621", 
	"msg": "non-zero return code", 
	"rc": 1, 
	"start": "2018-01-10 13:04:10.242521", 
	"stderr": " [error]  The command could not be executed successfully (returned:  [success] Cache rebuild complete.\n, code: 0) ",
	"stderr_lines": [" [error]  The command could not be executed successfully (returned:  [success] Cache rebuild complete.", ", code: 0) "], 
	"stdout": " [success] Cache rebuild complete.", "stdout_lines": [" [success] Cache rebuild complete."]
}
```
It seems like something has changed with the exit status of drush commands in [backend.inc](https://github.com/drush-ops/drush/blob/master/includes/backend.inc#L1011)??
