### ISSUE TITLE
drush 8.1.15 make on Windows 10 is not download projects

### ISSUE THREAD

**Issue by dmundra** [drush-ops/drush#3315]
On Windows 10, using Git bash with php 5.6.33 whenever I run drush make on the following make file it downloads core but not any of the modules:

```
core: 8.x
api: "2"
projects:
  drupal:
    version: "8.3.7"
  auto_entitylabel:
    version: "2.1-beta1"
  ctools:
    version: "3.0"
  diff:
    version: "1.0-rc1"
  externalauth:
    version: "1.0"
  imce:
    version: "1.6"
  ldap:
    version: "3.x-dev"
  pathauto:
    version: "1.0"
  restui:
    version: "1.15"
  simplesamlphp_auth:
    version: "3.0-rc3"
  token:
    version: "1.0"
  verf:
    version: "1.0-beta6"

  # SimpleSAMLphp Custom Attribute Mapping sandbox module
  simplesamlphp_custom_attributes:
    type: "module"
    download:
      type: "git"
      url: "https://git.drupal.org/sandbox/dmundra/2934777.git"
      branch: "8.x-1.x"
```

I just get the message, `No projects passed to drush_make_process`

Any insight would be appreciated.

Thank you
