### ISSUE TITLE
Using Drush aliases defined in drush.paths.alias-path config results in CommandNotFoundException

### ISSUE THREAD

**Issue by geerlingguy** [drush-ops/drush#3336]
## Steps to reproduce

Inside `~/.drush/drush.yml`:

```yaml
drush:
  paths:
    alias-path:
      - '${env.home}/.drush/sites'
```

Contents of `~/.drush/sites`:

```
~/.drush/sites $ ls
drupalvm.site.yml
```

Contents of `~/.drush/sites/drupalvm.site.yml`:

```yaml
# Ansible managed
drupalvm.test:
  host: 'drupalvm.test'
  options: {  }
  paths:
    drush-script: '/var/www/drupalvm/drupal/vendor/drush/drush/drush'
  root: '/var/www/drupalvm/drupal/web'
  uri: 'drupalvm.test'
  user: vagrant
  ssh:
    options: '-o "SendEnv PHP_IDE_CONFIG PHP_OPTIONS XDEBUG_CONFIG" -o PasswordAuthentication=no -i "${env.home}/.vagrant.d/insecure_private_key"'
```

If I'm in a Drupal project's root folder on my Mac with Drush Launcher 0.5.0 and Drush 9.0.0 installed, and I run `drush sa`, I see the alias printed to screen:

```
~/Sites/drupalvm/drupal/web $ drush sa
'@drupalvm.drupalvm.test':
  host: drupalvm.test
  options: {  }
  paths:
    drush-script: /var/www/drupalvm/drupal/vendor/drush/drush/drush
  root: /var/www/drupalvm/drupal/web
  uri: drupalvm.test
  user: vagrant
  ssh:
    options: '-o "SendEnv PHP_IDE_CONFIG PHP_OPTIONS XDEBUG_CONFIG" -o PasswordAuthentication=no -i "/Users/jeff.geerling/.vagrant.d/insecure_private_key"'
```

But when I try to _use_ the alias I get:

```
~/Sites/drupalvm/drupal/web $ drush @drupalvm.drupalvm.test status

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "@drupalvm.drupalvm.test" is not defined.  
```

If I log into my Drupal VM instance and use drush locally in the webroot it works fine. It also works fine if I have the alias defined in `[project-root]/drush/sites/drupalvm.site.yml`.

**Comment by geerlingguy** [comment]
Same thing happens inside Drupal VM with an alias file defined in a global aliases file:

```
vagrant@drupalvm:/var/www/drupalvm/drupal/web$ cat ~/.drush/sites/drupalvm.site.yml 
# Ansible managed
drupalvm.test:
  host: 'drupalvm.test'
  options: {  }
  root: '/var/www/drupalvm/drupal/web'
  uri: drupalvm.test
```

But inside the VM at least, if I go into to the docroot and run `drush [command]` things work since it can pick up the details from the site settings.php.
