### ISSUE TITLE
how to define rsync options in drush.yml

### ISSUE THREAD

**Issue by Schnitzel** [drush-ops/drush#3491]
I'm trying to add some rsync options in the `drush.yml`

I tried with

```
command:
  core:
    rsync:
      options:
        chmod: 'ugo=rwX'
```

but it's not working. While directly via
```
drush -d rsync @self:%files @lagoon.migration:%files -- --chmod=ugo=rwX
```
it works.

I assume the problem is because it needs `--` before the options.

Any idea how that works?

**Comment by greg-1-anderson** [comment]
Yeah, `--` converts everything after it from being interpreted as arguments rather than options. The Drush rsync command passes all of its extra arguments on to the shell rsync command that it exec's.

The consolidation/config feature to define additional command options in configuration does not work for additional arguments. The reason for this is that if an argument was defined in configuration, there would be no clear way to override or remove it.

Perhaps this behavior could be extended to include settings for additional options: things that appear after a `--` in the command line that themselves also start with `-` or `--`. Ideas about exactly how this should work would be welcome.

Strictly speaking, this would be a feature request for https://github.com/consolidation/config

**Comment by weitzman** [comment]
What about:

```
command:
  core:
    rsync:
      suffix:
        chmod: 'ugo=rwX'
```

**Comment by weitzman** [comment]
So, adding support for a 'suffix' key. ping @greg-1-anderson.

**Comment by greg-1-anderson** [comment]
Still not sure that we have 100% identified how this should behave. For example, what if the current drush.yml was configured as above, and the command line was:
```
drush -rsync @self:%files @lagoon.migration:%files -- --chmod=ugo=r
```
Would that result in `rsync --chmod=ugo=r` or `rsync --chmod=ugo=rxW --chmod=ugo=r`?

What if the configuration was `exclude: foo` and the commandline had `--exclude=bar`?  If the flags are both included, how would you get rid of `--exclude=--foo` if you didn't want it?

**Comment by Krilo89** [comment]
@Schnitzel, I'm with @greg-1-anderson on this. It is common that projects have drush .yml files inside it, so you can do a release to an Acceptation or Test environment with a release tool like Jenkins. All drush commands are executed but the rsync command doesn't include the --delete option right now.

Is anyone getting further with this issue?

**Comment by rudolfbyker** [comment]
Are boolean options supported? The following config

```yaml
command:
  core:
    rsync:
      options:
        exclude-paths: 'stats:error'
```

... adds `--exclude="stats" --exclude="error"` to the command, but 

```yaml
command:
  core:
    rsync:
      options:
        delete: true
```

does absolutely nothing.

Where is this stuff documented?
