### ISSUE TITLE
watchdog-show: JSON/YAML format does not filter by fields

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#3507]
When run:

    drush ws --fields=message --format=json

or:

    drush ws --fields=message --format=yaml

the output contains all fields, not the filtered one (`message`).

For example:

```
192879:
  wid: '192879'
  uid: '761'
  type: php
  message: 'Warning: array_key_exists() expects parameter 2 to be array, null given
  severity: warning
  link: ''
```
--

Drush Version   :  8.1.16
