### ISSUE TITLE
How to set --uri value when using command as a service

### ISSUE THREAD

**Issue by CaptainQuirk** [drush-ops/drush#3541]
Hi there !

I've been developing a drupal 8 module named **`factory_management`** with the following structure : 

```
src                                                                                                                                                                                                               
├── Form                                                                                                                                                                                                          
│   └── SitesListForm.php                                                                                                                                                                                         
└── Usine                                                                                                                                                                                                         
    └── SiteRepository.ph
```

I'm using a services.yml file to inject dependencies

```yml
services:
  state.commands:
    class: \Drush\Drupal\Commands\core\StateCommands
    arguments: ['@state']
    tags:
      -  { name: drush.command }
  factory_management.sites_list_form:
    class: Drupal\factory_management\Form\SitesListForm
    arguments:
        [ '@config.factory', '@factory_management.site_repository' ]
  factory_management.site_repository:
    class: Drupal\factory_management\Usine\SiteRepository
    arguments: [ '@state.commands' ]
```

I'm trying to read the `system.maintenance_mode` with the `StateCommands` in my `SiteRepository`, like so

```php
<?php

namespace Drupal\factory_management\Usine;

use Drush\Drupal\Commands\core\StateCommands;
use Symfony\Component\Finder\Finder;

class SiteRepository
{
    const SITES_DIR = DRUPAL_ROOT . DIRECTORY_SEPARATOR . 'sites';

    public $stateCommands;

    public function __construct(StateCommands $stateCommands)
    {
        $this->stateCommands = $stateCommands;
    }

    public function find()
    {
        $sites = [];
        $finder = new Finder();

        $finder
            ->directories()
            ->depth("== 0")
            ->in(self::SITES_DIR);

        foreach ($finder as $directory) {
            $site = [];

            $site['name'] = $directory->getRelativePathname();
            $site['maintenance'] = $this->getMaintenanceMode($site['name']);
            $sites[] = $site;
        }

        return $sites;
    }

    protected function getMaintenanceMode($siteName)
    {
        return $this->stateCommands->get('system.maintenance_mode');
    }
}
```

But I'm unable to find a way to use the `$siteName` parameter to set the equivalent of the `--uri` option. How can I do that ?

Thanks in advance !
