### ISSUE TITLE
Drush site:install ignores langcode tag from installation profile.

### ISSUE THREAD

**Issue by DerH4NNES** [drush-ops/drush#3663]
**Describe the bug**
Drush si seems to ignore langcode tags in installation profiles.

**To Reproduce**
What did you do?
I have a installation profile with a langcode: de tag in the info.yml. When I am installing my profile via browser the language selection step will be skipped and my installed language will be german. When I am installing it via drush si without "--locale=de" attribute then my installed page is english.

**Expected behavior**
When I am installing my profile via drush I am expecting that the info.yaml settings will be considered.

**Workaround**
drush si --locale=de

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.2-dev-g4bdbb590
| Drupal version? | 8.5.6
| PHP version     | 7.2.8-1
| OS?             | Linux

**Comment by TessaBakker** [comment]
@DerH4NNES Did you define the langcode as described in https://www.drupal.org/docs/8/creating-distributions/how-to-write-a-drupal-8-installation-profile ?
```
# Optional: Declare your installation profile as a distribution
# This will make the installer auto-select this installation profile.
# The distribution_name property is used in the installer and other places as
# a label for the software being installed.
distribution:
  name: Distribution Name
  # If you want your distribution to pre-select a language you can specify
  # the language code, as well. This will prevent the user from selecting
  # a language code in the user interface. While not recommended for generic
  # community distributions, this can be very useful for distributions that
  # are tailored to a language-specific audience (for example government
  # institutions in a certain country) but also site-specific installation
  # profiles. Note that this language code will also be used when installing
  # the site via Drush.
  langcode: de
``` 
Because Drupal core will only listen to that format (`includes/install.core.inc:461`)
