### ISSUE TITLE
Implement shell hooks

### ISSUE THREAD

**Issue by axel-rutz** [drush-ops/drush#3719]
**Is your feature request related to a problem? Please describe.**

As a deployment architect, i want to connect different components of my deployment workflow without PHP coding.

**Describe the solution you'd like**

In drush.yml (or another sensible place):
```
shell-hooks:
  sql-dump:
    post-command:
      - ../vendor/bin/my-custom-script.sh
  code-deploy: # Custom
    post-command:
      - ../vendor/bin/drush $TARGET cim -y
``` 

And then in our shell deployment script (this is the easy part):
```
#!/bin/bash
# ... [do deployment]
drush fire-hook code-deploy post-command
```
**Describe alternatives you've considered**

Currently we're coding PHP, which is tedious for small issues.

**Additional context**

For us, and presumably many others, this will make a huge increase in the usefulness of drush. We'd be able to maintain deployment config with other drush config.

Note that at least lando and ddev implement shell hooks like this for their platforms.

Alas, if drush does not leverage the idea, doing this in contrib would need an equivalent of hook_module_implements_alter for the HookManager, to register the config stuff there.
