### ISSUE TITLE
sql:sync fails to dump the remote database and retrieves corrupted dump

### ISSUE THREAD

**Issue by cristiroma** [drush-ops/drush#3816]
**Describe the bug**
Using drush sql:sync to get the production dump retrieves a partial broken dump

**To Reproduce**
On production server, the website has a huge `cache_data` and the `max_allowed_packet` is set to MySQL maximum size: `1073741824`.

I am running `../vendor/bin/drush -v @site1 sql:sync @site1.prod @self`

**Expected behavior**
I expect the command to fail, because on the remote server the `mysqldump` command failed with:

```
mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' bytes when dumping table `cache_data` at row: 91
```

**Actual behavior**
Instead of failing, a partial dump is written to SQL file, retrieved and imported without any failure. The resulting local instance is broken, having just the following tables:

```
+-------------------------------------+
| Tables_in_site1                     |
+-------------------------------------+
| batch                               |
| block_content                       |
| block_content__body                 |
| block_content__field_title          |
| block_content_field_data            |
| block_content_field_revision        |
| block_content_revision              |
| block_content_revision__body        |
| block_content_revision__field_title |
| cache_bootstrap                     |
| cache_config                        |
| cache_container                     |
| cache_data                          |
| cache_default                       |
| cache_discovery                     |
| cache_entity                        |
| cache_menu                          |
+-------------------------------------+
```

**Workaround**
Workaround is to run the drush command with the following arguments:

`../vendor/bin/drush -v  @site1 sql:sync --structure-tables-list='cache,cache_*,watchdog' @site1.prod @self`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.4.0
| Drupal version? | 8.6.4
| PHP version     | 5.6/7.1 (both fail)
| OS?             | Linux

**Additional information**

1. I tried to hard-code the option `structure-tables-list` inside the `site1.site.yml` without luck:

```
prod:
  command:
    core:
      rsync:
        options:
          exclude-paths: 'css/:js/:styles/:php/:xmlsitemap'
    sql:
      sync:
        options:
          structure-tables-list: 'cache,cache_*,watchdog'
```

2. Drush command --help is incorrect (it says cache* are default ignored) but that's not the case.

```
 ../vendor/bin/drush sql:sync --help

 --structure-tables-list=STRUCTURE-TABLES-LIST A comma-separated list of tables to include for structure, but not data. [default: "cache,cache_*,watchdog"]
```

**Comment by weitzman** [comment]
Thanks for the report.

Please upgrade to latest release.

Then please paste output with `-vvv`. Also, please run the same mysqldump command that you see in the output. Does that command return a 1 exit code? If so we have a chance at catching that and stopping further operations.

**Comment by cristiroma** [comment]
1. Upgraded to 9.5.2 - the bug is still there
2. Here's the output - https://pastebin.com/gjrEZU4K
3. I ran the command from the console (without --defaults-file) and strangely worked without fail.

```
mysqldump -u USER -pPASSWORD  db_prod --host=localhost --port=3306 --no-autocommit --single-transaction --opt -Q  | gzip -f > /tmp/test.sql.gz
```
I've tried with --host=127.0.0.1 - same result. (Running Debian GNU/Linux 8 (jessie))

4. How can I check the -1 exit code.

**Comment by weitzman** [comment]
[Check last command's exit code](https://bencane.com/2014/09/02/understanding-exit-codes-and-how-to-use-them-in-bash-scripts/)

I'm pretty sure that mysqldump is not returning an erorr or else it would get caught by https://github.com/drush-ops/drush/blob/3f3449d8fdf712499f28d73617d919f60cd47d97/src/Sql/SqlBase.php#L153-L160. Without a mysqldump error, there is nothing drush can reasonably do.

**Comment by weitzman** [comment]
try defining your structure tables on sql:dump instead of sql:sync

**Comment by greg-1-anderson** [comment]
We need to set pipefail, as described in the [first answer of this question](https://stackoverflow.com/questions/29502717/exit-status-of-a-piped-command-executed-over-ssh).

**Comment by cristiroma** [comment]
> try defining your structure tables on sql:dump instead of sql:sync

I've tried your suggestion and does not seem to work:

```
prod:
  uri: ...
  root: ...
  host: ...
  command:
    core:
      rsync:
        options:
          exclude-paths: 'css/:js/:styles/:php/:xmlsitemap'
    sql:
      sync:
        options:
          structure-tables-list: 'cache,cache_*,watchdog'
      dump:
        options:
          structure-tables-list: 'cache,cache_*,watchdog'
```

I did some debugging and the `$options['structure-tables-list']` which gets passed is not passed along to the spawned drush process here:

https://github.com/drush-ops/drush/blob/3de56d4e169066ee7ccc2f07028503a6b2993d86/src/Commands/sql/SqlSyncCommands.php#L133-L144

**Comment by cristiroma** [comment]
Sorry I did a mistake in my previous comment. To add more context I have a multi-site setup and have two files: `self.site.yml` and `site3.site.yml`

When I debug, the parameters from `self.site.yml` are picked as parameter to `dump($options) ` function though do not get passed to remote drush

1. `self.site.yml` where I have:
```
site3:
  uri: site3
  command:
    sql:
      sync:
        options:
          structure-tables-list: 'cache,cache_*,watchdog'
```


2. `site3.site.yml` - declaring the option here does not pass any parameter. Probably makes sense since I initiate the command from my computer.

```
prod:
  uri: 
    sql:
      sync:
        options:
          structure-tables-list: 'cache,cache_*,watchdog'
```
