### ISSUE TITLE
drush-script doesn't work on remote site 

### ISSUE THREAD

**Issue by arrubiu** [drush-ops/drush#3850]
I'm trying to use drush 9.5.2, on local machine, to execute commands on a remote site that has drush 8.x.
I've converted my alias to new version, in yml, here is:

```
live:
  host: www.mysite.com
  options:
    db-allows-remote: true
    db-url: 'mysql://drupal:drupal@mariadb/drupal'
  paths:
    drush-script: '/home/wodby/.composer/vendor/drush/drush/drush.php'
    files: files
  root: /var/www/html
  ssh:
    options: '-p 9191 -o "AddressFamily inet" -o "StrictHostKeyChecking=no"'
  uri: www.mysite.com
  user: wodby
```
The ssh connection is ok, but if I try to execute drush @d8.live status I obtain:

`bash: php: command not found`

If I login to the remote server and I execute the drush-script, it works.
Which could be the problem?

Thanks.
