### ISSUE TITLE
Support Req: Defining path to PHP in remote alias

### ISSUE THREAD

**Issue by bleen** [drush-ops/drush#3977]
**Describe the bug**
In drush <= 8 I could define the path to the correct PHP cli to use for remote commands directly in the remote alias definition: 

```
$aliases['example'] = array(
  'php' => '/path/to/php/on/the/server'
);
```
I've tried various permutations of this in my yml alias file that I use now that I'm using drush9 but nothing appears to work. 

Some examples I've tried:
```
prod:
  ...
  php: '/usr/local/php71/bin/php'
  paths:
    drush-script: '/home/username/sites/ps267.org/web/vendor/bin/drush'
    files: '/home/username/sites/ps267.org/web/sites/default/files'
```
or
```
prod:
  ...
  paths:
    drush-script: '/home/username/sites/ps267.org/web/vendor/bin/drush'
    files: '/home/username/sites/ps267.org/web/sites/default/files'
    php: '/usr/local/php71/bin/php'
```

I've tried other, but to no avail... any help would be greatly appreciated
