### ISSUE TITLE
Set environment variables in aliases

### ISSUE THREAD

**Issue by geek-merlin** [drush-ops/drush#4170]
**The problem**

When invoking remote drush, quite often it's handy to set environment variables.

Just today i stumbled on an instance of #3850 where the cleanest thing to do would be to set remote $PATH.

From  example.site.yml;

> SSH site aliases may no longer _set_ environment variables.
> This is a planned feature.
 
**Describe the solution you'd like**

Pick up alias env_vars key and set env vars.

**Comment by weitzman** [comment]
Thanks for filing this.

If you are trying to set the /path/to/drush, you can use %drush-script for that. Paths for other stuff like `php`, `mysql`, `mysqldump` cant be done with in drush until this feature is in.

**Comment by greg-1-anderson** [comment]
I forgot we didn't do this yet. 😬

**Comment by geek-merlin** [comment]
Good to know it's agreed this is wanted ;-).

Dug a bit in the code and, wooooot, ye olde code `$env_vars = $site_record['#env-vars'];` is still there. I succeeded to set a $PATH via:

```
dev:
  host: somehost
  user: someuser
  root: /var/www/html/docroot
  uri: dev.consent.mbm.wod.by
  ssh:
    options: '-p 31382'
  "#env-vars":
    PATH: /usr/local/sbin:/usr/local/bin
```
