### ISSUE TITLE
Add support for docker-compose options in aliases

### ISSUE THREAD

**Issue by orlandothoeny** [drush-ops/drush#4174]
**Problem**
Currently it is possible to use the following alias configuration to execute commands inside a docker-compose container named `drupal`:
```
local:
  root: /app/docroot
  docker:
    service: drupal
  uri: 'http://localhost'
```

My problem:
We have two docker-compose files.
One for the server environments, and one for local development.
```
docker-compose.dev.yml
docker-compose.yml
```
Currently, Drush always uses the file named `docker-compose.yml`.
By setting the `-f` flag, this can be altered: https://docs.docker.com/compose/reference/overview/

**Possible solution**
Add a configuration option below the `docker` alias option.
Example:
```
local:
  root: /app/docroot
  docker:
    service: drupal
   compose:
     options:
       - '-f docker-compose.dev.yml'
  uri: 'http://localhost'
```
Analogue to the `exec: options:` option: https://github.com/drush-ops/drush/blob/master/examples/example.site.yml#L141
