### ISSUE TITLE
Wrong site aliases

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#4191]
**Describe the bug**
I am not sure if this is a feature or a bug but it is confusing. In some cases Drush mixes up site aliases.

**To Reproduce**
1. Create two alias files
```yaml
# drush/sites/self.site.yml
foo:
  uri: 'https://foo.example.com'
```
```yaml
# drush/sites/bar.site.yml
bar:
  uri: 'https://bar.example.com'
```
2. Run `drush sa` command

**Expected behavior**
```
'@bar.bar':
  uri: 'https://bar.example.com'
'@self.foo':
  uri: 'https://foo.example.com'
```

**Actual behavior**
```
'@bar.bar':
  uri: 'https://bar.example.com'
'@bar.foo':
  uri: 'https://foo.example.com'
'@self.foo':
  uri: 'https://foo.example.com'
```

Note `@bar.foo` alias. It's not defined anywhere.
### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.0.0-rc1 
| Drupal version? | 8.x
| PHP version     | 7.3
| OS?             | Linux

**Additional information**
This might be a scope of consolidation/site-alias project.
