### ISSUE TITLE
rsync with exclude-paths inside site aliases not working

### ISSUE THREAD

**Issue by jcmartinez** [drush-ops/drush#4382]
**Describe the bug**
In previous versions I used to define rsync exclude-paths inside the site aliases file. I'm trying to do the same but it doesn't work.

**To Reproduce**
According to https://github.com/drush-ops/drush/blob/master/examples/example.site.yml
```
#   command:
#     sql:
#       sync:
#         options:
#           no-dump: true
```
Following this logic, I have configured my site alias files with:

```
  command:
    rsync:
      mode: rlptz
      exclude-paths: 'css:imagecache:ctools:js:tmp:php:styles:'
```
I have also tried:
```
  command:
    rsync:
      mode: rlptz
      exclude-paths:
        - 'css:'
        - 'imagecache:'
        - 'ctools:'
        - 'js:'
        - 'tmp:'
        - 'php:'
        - 'styles:'
```

**Expected behavior**
I expected the mode and the exclude-paths to be used.

**Actual behavior**
Neither the mode or the exclude paths are picked up.

**Workaround**
I have been able to exclude the paths by typing them directly on the command line:
```
drush -v --exclude-paths=:css:imagecache:ctools:js:tmp:php:styles: rsync @drushaliases.sitename.com:%files/ @drushaliases.sitename.dev:%files
```
but this is very inconvenient because I have to remember to type them always.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.2
| Drupal version? | 8.8.5
| PHP version     | 7.2.29
| OS?             | Linux

**Comment by weitzman** [comment]
try:

```
command:
   core: 
    rsync:
      mode: rlptz
      exclude-paths: 'css:imagecache:ctools:js:tmp:php:styles:'
```

**Comment by jcmartinez** [comment]
Thanks @weitzman, for pointing me on the direction:.

This is how it actually works:

```
  command:
    core:
      rsync:
        options:
          mode: rlptz
          exclude-paths: 'css:imagecache:ctools:js:tmp:php:styles:'
```
Happy to create a PR to add this snippet to the documentation.
