### ISSUE TITLE
ability to include a local drush.yml file

### ISSUE THREAD

**Issue by hanoii** [drush-ops/drush#4662]
I am looking for a way to include a local drush.yml file that can be ignored so I can push a set of default drush.yml to the repo but that some things can be overridden locally if needed.

~I think (haven't looked yet) that probably https://github.com/consolidation/config is what I should use but I wonder if this shouldn't also be supported within drush.~

A logical way I thought about this was to have on my `PROJECT/drush/drush.yml`:

```yml
drush:
  paths:
    # Specify config files to load.
    config:
      # Load any personal config files. Is silently skipped if not found. Filename must be drush.yml
      - local/drush.yml
```

This only works if I am on PROJECT/drush.

If I could add a config file relative to the drupal root something like this can be easily done, like `- ${DRUPAL_ROOT}/...`

I wonder if it isn't better to add the DRUPAL_ROOT somehow to the whole drush environment so that you can do `- ${env.DRUSH_DRUPAL_ROOT}` from here as well as other parts.
