### ISSUE TITLE
Win10 & Drush configuration

### ISSUE THREAD

**Issue by tyler36** [drush-ops/drush#4687]
**Describe the bug**
Recently I can across a post about using a drush config file to reduce typing. I often use the `site-install` command so this looked like a great way to set a default 'account-name' / 'account-pass'.

But I can't seem to get Drush to read the config file.

**To Reproduce**
In my `~/.drush/drush.yml` file, I have this set.
```yml
  site:
    install:
      options:
        # Set a predetermined username and password when using site-install.
      account-name: 'admin'
      account-pass: 'drupal-admin'
```

I have a `composer` based Drupal 9.1 install with Drush in: `~/ddev/dev-9.1`.  So, I open a terminal at `~/ddev/dev-9.1`:
```bash
> drush status
...
Drupal version   : 9.1.5
Drush version    : 10.4.0
```
So, drush is working.
```bash
> drush si --site-name=monkey
...
 [success] Installation complete.  User name: admin  User password: LzDnGhjqJZ
```
- The site name is set ("monkey") but the `admin` user password is not set to `drupal-admin`, it's `LzDnGhjqJZ`.

Config file states that these locations are checked for config files:
```yml
# 1.  Drupal site folder (e.g. sites/{default|example.com}/drush.yml).
# 2.  Drupal /drush and sites/all/drush folders, or the /drush folder
#       in the directory above the Drupal root.
# 3.  In any location, as specified by the --config (-c) option.
# 4.  User's .drush folder (i.e. ~/.drush/drush.yml).
# 5.  System wide configuration folder (e.g. /etc/drush/drush.yml or C:\ProgramData\Drush\drush.yml).
```
- `#2` - I create a folder `~/ddev/dev-9.1/drush` and copied the `drush.yml` file into here .. and it doesn't work
- `#3` - try running explicitly without luck
```bash
drush si --site-name=monkey -c .\drush\drush.yml
```
- `#4` - what I assumed was my original attempt but no luck
- `#5` - ` /etc/drush/drush.yml` doesn't exist on Win10, and `C:\ProgramData\Drush` is a Win10 path but is not set on my PC. I created the folder and copied my `drush.yml` file into it but no luck.

I must be missing something easy here right? What can I try next?

**Expected behavior**
Expect Drush to use config file.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.0
| Drupal version? | 9.1.5
| PHP version     | 7.3.24
| OS?             |  Windows 10

**Comment by weitzman** [comment]
You are missing `command` at the top level. Quoting from https://www.drush.org/latest/examples/example.drush.yml/, it should be 

```
command:
  site:
    install:
      options:
        # Set a predetermined username and password when using site-install.
#       account-name: 'alice'
#       account-pass: 'secret'
```

I guess its easy to miss this level in the docs. Sorry about that.

**Comment by tyler36** [comment]
Thank you for the update.

Sorry, I wasn't clear, I do have `command` in the file. The only changes I made to the file was:
- Uncomment the `account-name` and set it as `admin`
- Uncomment the `account-pass` and set it as 'drupal-admin'

Your comment seems to suggest that I only need those lines to get it working. So, my `~/.drush/drush.yml`  file, in-full:
```yml
command:
  site:
    install:
      options:
      account-name: 'admin'
      account-pass: 'drupal-admin'
```

I tried running `drush si` again and it did not work.

**Comment by weitzman** [comment]
Indent the account lines two more spaces.

**Comment by tyler36** [comment]
Nope.

My file has the spaces, I must have typed it out incorrectly in the post. I double-checked the file and have added the space count at the the end of the line:
```yml
command: (0)
  site: (2)
    install: (4)
      options: (6) 
        account-name: 'admin' (8)
        account-pass: 'drupal-admin'(8)
```
