### ISSUE TITLE
`include:` is different in Documentation and `example.drush.yml`

### ISSUE THREAD

**Issue by macmladen** [drush-ops/drush#4740]
**Describe the bug**
I was trying to add a path to the `drush.yml` to recognize the `radix` theme command but it did not work (most likely because I do not do it right).

**To Reproduce**

I used the code from documentation but I didn't make it with namespaces. I did not understand and copy/paste did not work

     [preflight] Unable to parse at line 8 (near "  include:").

Commenting namespaces did help to parse without errors but `drush` did not find the command as it would with `--include` directive (indent ajdusted accordingly)

```
drush:
  paths:
    config:
      # Load any personal config files. Is silently skipped if not found. Filename must be drush.yml
      - ${env.HOME}/.drush/config/drush.yml
    include:
#    'Commands/example_drush_extension': '${env.PWD}'
#      include:
      - '${env.HOME}/.drush/commands'
      - /usr/share/drush/commands
#    'Commands/radix': '${env.PWD}'
#      include:
      - /var/www/html/web/themes/contrib/radix
```

This is proper absolute path and is should work. I also tried `${env.PWD}/web/themes/contrib/radix` which I suppose should work too? (is the `${env.PWD}` actually an `$app_root`?)

**Expected behavior**
`drush` should list command just as it lists with `--include`

**Actual behavior**
It does not.

**Workaround**
When I use `drush --include="web/themes/contrib/radix"` I get proper `radix:create (radix)` command.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 104.3
| Drupal version? | 9.1.7
| PHP version     | 7.3
| OS?             | Linux (Mac Intel, ddev, Docker 3.1.0. build 51484 Engine 20.10.2)
| Drush configs    | /var/www/html/vendor/drush/drush/drush.yml 
|                   | /var/www/html/drush/drush.yml              

**Additional information**
I would like to understand **namespaces** so can someone include proper namespace and `include:` for **Radix** theme which is in the `web/themes/contrib/radix`?

**Comment by macmladen** [comment]
OK _mea culpa_, I didn't structure properly `include:` is not under `paths:` but it is directly under `drush`.

>  (is the ${env.PWD} actually an $app_root?)

Yes, it is. If invoked with debug switch `drush -d` it will show and use directories **if they exist** otherwise you will not see them.

Still I did not make it with **namespace** include?

**Comment by macmladen** [comment]
It is not my mistake: it is documented that way in `/examples/example.drush.yml` so either is that a mistake or on documentation, https://www.drush.org/latest/using-drush-configuration/#specify-folders-to-search-for-drush-command-files

Apparently, that way works (what is documentation) and this does not but confuses.

**Remark**: maybe there could be other inconsistencies in the code/doc/example.

```
# Preflight configuration.
drush:
  paths:
    config:
      # Load any personal config files. Is silently skipped if not found. Filename must be drush.yml
      - ${env.HOME}/.drush/config/drush.yml
    include:
      - '${env.HOME}/.drush/commands'
      - /usr/share/drush/commands
    alias-path:
      - '${env.HOME}/.drush/sites'
      - /etc/drush/sites
```

**Comment by macmladen** [comment]
When using `drush -d`, **alias-path** is ignored either under `drush` (as in Documentation) and under `drush:paths` (as in `example.drush.yml`

```
drush:
  alias-path:
    - '${env.HOME}/.drush/sites'
    - /etc/drush/sites
```

**Comment by weitzman** [comment]
Thanks for reporting the discrepancy with --include docs. #4747 fixes it.

Your alias-path should work once you nest it under `drush.paths`. If it doesn't, I'm curious if alias-path is defined in var/www/html/drush/drush.yml? If not, where?

**Comment by macmladen** [comment]
This is a different issue with `alias-path` so I can make a new issue if you wish?

I tested and here is how it operates (same environment, same project, **ddev** based but checked while logged into the container, i.e. from Linux).

If I have only defined it here `$PROJECT/drush/drush.yml` **it did not work**:

```
drush:
  include:
    - '${env.HOME}/.drush/commands'
    - /usr/share/drush/commands
    - '${env.PWD}/web/themes/contrib/radix'
  paths:
    config:
      # Load any personal config files. Is silently skipped if not found. Filename must be drush.yml
      - '${env.HOME}/.drush/config/drush.yml'
    alias-path:
      - '${env.HOME}/.drush/sites'
      - /etc/drush/sites
```
```
~/.drush $ drush -d sa
 [preflight] Config paths: /var/www/html/vendor/drush/drush/drush.yml,/var/www/html/drush/drush.yml
 [preflight] Alias paths: /var/www/html/web/drush/sites,/var/www/html/drush/sites
 [preflight] Commandfile search paths: /var/www/html/vendor/drush/drush/src,/var/www/html/drush
```

However, adding an `$HOME/.drush/drush.yml` with `alias-path` **it worked**

```
drush:
  paths:
    alias-path:
      - '${env.HOME}/.drush/sites'
      - /etc/drush/sites
```

```
~/.drush$ drush -d sa
 [preflight] Config paths: /home/mladen/.drush/drush.yml,/var/www/html/vendor/drush/drush/drush.yml,/var/www/html/drush/drush.yml
 [preflight] Alias paths: /home/mladen/.drush/sites,/etc/drush/sites,/var/www/html/web/drush/sites,/var/www/html/drush/sites
 [preflight] Commandfile search paths: /var/www/html/vendor/drush/drush/src,/var/www/html/drush
```
