### ISSUE TITLE
Command options configured in the drush alias file do not get used by the command

### ISSUE THREAD

**Issue by edwardcrompton** [drush-ops/drush#4797]
**Describe the bug**
Command options configured in the drush alias file do not get used by the command.

**To Reproduce**
Some of my remote aliases require the mysql socket to be specified by passing an option to the drush command like this:

`drush @stage sql-query "SHOW tables;" --extra="-S /var/lib/mysql/mysql.sock"

Rather than add this option manually every time I run an sql command, I wanted to configure it in my alias file like this:

```
stage:
  host: ...
  root: ...
  user: ...
  uri: ...
  paths:
    drush-script: ...
  ssh:
    options: -tt -o PasswordAuthentication=no
    tty: true
  command:
    sql:
      query:
        options:
          extra: '-S /var/lib/mysql/mysql.sock'
```

According to the documentation [here](https://github.com/drush-ops/drush/blob/10.3.6/examples/example.site.yml) this should work. However, when I then run this:

`drush -vvv @stage sql-query "SHOW tables;"`

I can see in the output:

```
The command "ssh -t -tt -o PasswordAuthentication=no user@server.org '/var/www/.../drush -vvv sql-query '\''SHOW tables;'\'' --uri=... --root=...'" failed.
```

**Expected behavior**
I would have expected the second command above to run correctly like the first one (where I explicitly specified the option). I would also have expected the option to have been included in the ssh command shown above.

**Actual behavior**
The second command fails. The option is not added to the ssh command issued by drush.

**Workaround**
Add options manually to each command as required. 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.5.0
| Drupal version? | 8.9.17
| PHP version     | 7.4
| OS?             | Linux

**Additional information**
