### ISSUE TITLE
Drush warnings with php 8.0

### ISSUE THREAD

**Issue by nalakafernando** [drush-ops/drush#4914]
**Describe the bug**
While using drush aliases with drush9/10 (php8.0) a deprecation warning gets generated. 

```
~/Sites/devdesktop/drupal-9-project-9.0.3$ vendor/bin/drush @broken.dev uli
 [warning]  does not appear to be a resolvable hostname or IP, not starting browser. You may need to use the --uri option in your command or site alias to indicate the correct URL of this site.

Deprecated: Required parameter $args follows optional parameter $command in /usr/local/drush10/vendor/drush/drush/includes/batch.inc on line 116

Deprecated: Required parameter $options follows optional parameter $command in /usr/local/drush10/vendor/drush/drush/includes/batch.inc on line 116
http://eemmadisondev.prod.acquia-sites.com/user/reset/1/1638786618/yJN8o5QkTvpHF5KLdXaVDlWf8cKcdvVELPW4Vw9odAo/login
```

**To Reproduce**
- Setup a local drupal site running drush 10.6.1
- Setup drush aliases for the remote site, drush-script would be drush9 or drush10
```
dev:
  root: /var/www/html/docroot
  ac-site: test
  ac-env: dev
  ac-realm: prod
  uri: test.prod.acquia-sites.com
  dev.livedev:
    parent: '@test.dev'
    root: /mnt/gfs/test.dev/livedev/docroot
  host: test.ssh.prod.acquia-sites.com
  user: test.dev
  paths:
    drush-script: drush9
```
- Try a `uli` command to the remote drupal site (php8.0)
- Warnings gets generated

**Expected behavior**
- The command should run seamlessly without warnings, sometimes the functionality breaks with these. 

**Actual behavior**
- Warnings gets generated and uli sometimes doesnt work. 

**Workaround**
- Removing the below fixes this issue for now in my environment 
```
paths:
    drush-script: drush9
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.0 , 10.3.4
| Drupal version? | 9.2.10
| PHP version     | 8.0.13
| OS?             | Mac

**Additional information**

- IF can be done, It would be great to check the php version and rearrange the code accordingly to comply with php 8.0 version
