### ISSUE TITLE
Docker Compose V2 compatability

### ISSUE THREAD

**Issue by jon-nunan** [drush-ops/drush#4957]
NOTE: I think this is more a bug with Docker Compose V2, and should be fixed in that project.  Just wanted to add it here so people would be aware.

**Describe the bug**
Docker Desktop seems to be rolling out its Docker Compose V2 in batches.  When it enabled automatically for me, my local drush aliases with docker failed.

**To Reproduce**
Be using Docker Compose V2
![image](https://user-images.githubusercontent.com/124704/147726012-334a291b-5cbe-4f99-895a-0cc475f97a3a.png)

have a site alias file like: 
```
local:
  root: /var/www/html/my-site/web
  uri: https://my-site.local
  docker:
    service: php
    compose:
      options: --env-file ../websites-dev-environment/.env -f ../websites-dev-environment/docker-compose.yml
```
run a command like `drush @self.local status`

**Expected behavior**
Drush to work like normal

**Actual behavior**
![image](https://user-images.githubusercontent.com/124704/147726104-235367af-a55f-4f31-b89b-901d326900a9.png)

**Workaround**
Strangely copying the docker-compose command that it says is failing, and running it with no modifications seems to work still. I see issues in their (docker/compose) queue about tty problems.

Out of interest I tried adding `-T` to the exec.options in the alias file and the command works again but the output is a bit broken, so not ideal.

Ultimately I just went back to v1, see instructions here: https://docs.docker.com/compose/cli-command/

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.1
| Drupal version? | 9.2.7
| PHP version     | 7.4
| OS?             | Windows (though in a WSL Ubuntu install)

**Additional information**

**Comment by jon-nunan** [comment]
Actually found https://github.com/docker/compose/issues/8833#issuecomment-953023240
so changing alias file to 
```
local:
  root: /var/www/html/my-site/web
  uri: https://my-site.local
  docker:
    service: php
    compose:
      options: --env-file ../websites-dev-environment/.env -f ../websites-dev-environment/docker-compose.yml </dev/null
    exec:
      options: -T
```
seems to work for me
