### ISSUE TITLE
Drush extra-dump options cannot be specified to only apply to certain db types

### ISSUE THREAD

**Issue by tobybellwood** [drush-ops/drush#5145]
In Lagoon, we provide a generic drush.yml file in our base images. We are wanting to add some additional options to this file, to control the behaviour of `mysqldump`/`pg_dump` particularly, mostly around the consumption of command line switches and environment variables that would ordinarily (in mariadb/mysql anyway) be specified in the my.cnf file.

I know the backstory around `default-files` and `extra-default-files`, and fully appreciate why Drush is configured the way it is, and hence why the my.cnf goes unread.

Our current issue (hinted below) is that it is desirable to be able to configure the MARIADB_MAX_ALLOWED_PACKET variable on a per-environment basis (and we do, in my.cnf). However, updating the drush.yml to include this in an extra-dump command will immediately break dumps for anyone who uses PostgreSQL without first specifying their own drush.yml over the top of ours

What we are pondering is whether either of the following would be desirable to have as a standard Drush method (of course with a standard fallback to the current operation if neither of these keys are specified):

* introducing the ability to specify the `options` to command.sql.dump that if provided only applied to a specific SQL implementation

```
command:
  sql:
    dump:
      options:
        mysqldump:
		  extra-dump: --no-tablespaces --max_allowed_packet=${env.MARIADB_MAX_ALLOWED_PACKET}
		pg_dump:
		  extra-dump: --no-tablespaces 
```    
* or prefixing the *.dump.options with the db-driver to allow for potential other switches or configuration to be passed (if we could ever think of any)

```
command:
  mysql:
    dump:
      options:
        dump:
		  extra-dump: --no-tablespaces --max_allowed_packet=${env.MARIADB_MAX_ALLOWED_PACKET}
  pgsql:
    dump:
      options:
        dump:
		  extra-dump: --no-tablespaces 
```    

We've thrown this backwards an forwards internally and haven't come to a satisfactory answer in Lagoon that won't imposition either mysql/mariadb or PostgreSQL users, and figured it was worth asking upstream if this is something we could contribute if you're willing to consider it?

(as a side question/thought experiment, is thereactually a way to trigger a drush sql command on mysql with `hide_password` set to false, to remove the defaults-file and allow my.cnf to be read?)
