### ISSUE TITLE
Drush command is picked up from the Drupal services file

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#5245]
**Describe the bug**

A custom Drupal module has this in its mymodule.services.yml file:

```
services:
  load_favicons_command.commands:
    class: \Drupal\wsd_favicon_loader\Commands\ScheduleForLoadFaviconsCommand
    tags:
      - { name: drush.command }
```

The command is shown when I do `drush list`. There is no drush.services.yml file.

This behaviour isn't documented at https://www.drush.org/latest/commands/

**Expected behavior**

I don't know. This is either:

a. undocumented expected behaviour
b. a bug
c. support for a deprecated way of doing this -- a warning would be useful?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.1.1
| Drupal version? | 9.4
| PHP version     | 8.0.8
| OS?             | Mac

**Additional information**
