### ISSUE TITLE
sql:sync command does not pass down options to sql:dump (ex: structure-tables-list)

### ISSUE THREAD

**Issue by jcowher** [drush-ops/drush#5388]
**Describe the bug**
Given a `drush.yml` like the following, I would expect that options like `structure-tables-key` be passed down to the `sql:dump` command. I only want to add the `structure-tables-key` during a sync and not when `sql:dump` is executed outside of the `sql:sync` command (ex: during deployments).

```
command:
  sql:
    dump:
      options:
        extra-dump: --no-tablespaces
    sync:
      options:
        structure-tables-key: sync

sql:
  structure-tables:
    sync:
      __acquia_monitoring
      - batch
      - cache
      - cache_*
      - history
      - locale_file
      - migrate_*
      - openid_connect_authmap
      - queue
      - semaphore
      - sessions
      - tmgmt_*
      - watchdog
```

### Workaround
I've added a `@hook replace-command sql-sync` command and overwrote the `dump()` method in my command class.

```
/**
 * Overrides Drush's sql:sync command.
 *
 * @hook replace-command sql-sync
 */
public function sync($source, $target, $options = ['no-dump' => false, 'no-sync' => false, 'runner' => self::REQ, 'create-db' => false, 'db-su' => self::REQ, 'db-su-pw' => self::REQ, 'target-dump' => self::REQ, 'source-dump' => self::OPT, 'extra-dump' => self::REQ]): void {
  parent::sqlsync($source, $target, $options);
}

/**
 * {@inheritdoc}
 */
public function dump(array $options, array $global_options, SiteAlias $sourceRecord): string {
  // Many options from the sql:sync command are ignored by the parent dump method.
  if (isset($options['structure-tables-key'])) {
    $global_options['structure-tables-key'] = $options['structure-tables-key'];
  }

  return parent::dump($options, $global_options, $sourceRecord);
}
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.4
| Drupal version? | 9.5
| PHP version     | 8.0
| OS?             | Mac/Linux/Windows
