### ISSUE TITLE
Allow passing arguments via drush config 

### ISSUE THREAD

**Issue by tyler36** [drush-ops/drush#5549]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set arguments in a `drush.yml` file for site install.

After some research, I found I could use the following line on CLI:

`drush site-install standard install_configure_form.date_default_timezone="Asia/Tokyo"`

I would like to be able to set this in the `drush.yml` config file.

I use DDEV (often with Gitpod) for spinning up test sites.
I love how simple `site-install` is and the ability to pass options is great.

I have a `.yml` file in my home directory that sets some basic stuff including locale.
One thing I often forget is the default timezone though.

**Describe the solution you'd like**

In addition to setting site install options, a developer should be able to set profile arguments.

```yml
command:
  site:
    install:
      options:
        site-name: "${env.DDEV_PROJECT}"
        account-name: 'admin'
        account-pass: 'secret'
        locale: 'ja'
    # Set profile and additional arguments
    profile:
      standard:
        install_configure_form.date_default_timezone: "Asia/Tokyo"
```

**Additional context**

Ideally, anything in the `install_configure_form` context should be available. 
It feels like this would also help #1166 

Apologies if this documented somewhere. I was unable to find anything.
