### ISSUE TITLE
Cannot inject service parameters

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#5586]
**Describe the bug**

I have a Symfony console command registered in Drush as follows.

```yml
services:
  my_module.example
    class: Drupal\my_module\Command\ExampleCommand
    arguments: ['%app.root%', '@entity_type.manager']
    tags:
      - { name: console.command }
```

By some reason the `%app.root%` parameter is no longer resolved in the command.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.0-RC1
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Additional information**
That works well in Drush 12.0-beta1 and below.
