### ISSUE TITLE
Drush 11 has "config.import.commands" but not in 12.

### ISSUE THREAD

**Issue by rajeshreeputra** [drush-ops/drush#5626]
**Describe the bug**
I am using "config.import.commands" in my module with drush/drush 11.5.1 after upgrade to drush/drush 12 it is not working and not able to find any upgrade path on drush.org.

**To Reproduce**
In custom modules use drush.services.yml file contains below code.
```
services:
  my_module.config_commands:
    class: 'Drupal\my_module\Commands\ConfigImportCommands'
    arguments:
      - '@config.storage'
      - '@config.import.commands'
      - '@string_translation'
      - '@module_handler'
      - '@class_resolver'
    tags:
      - { name: drush.command }
 ```
"config.import.commands" service has been removed from the 12. Now upgrading to drush 12 throws error.
Can we have upgrade path forward.
