### ISSUE TITLE
Allow using rsync from Docker container on the server

### ISSUE THREAD

**Issue by back-2-95** [drush-ops/drush#5912]
**Is your feature request related to a problem? Please describe.**
I would like to be able to rsync files and sql-syncs from a virtual server which has Drupal running as Docker container.

**Describe the solution you'd like**

```yaml
dev:
  host: somehost
  user: deployment
  uri: https://some-site.tld
  paths:
    drush-script: '/usr/local/bin/drush-script'
    rsync-script: '/usr/local/bin/rsync-script'
```

/usr/local/bin/drush-script: (this works):

```shell
#!/bin/bash

docker exec drupal-container drush --ansi $@
```

/usr/local/bin/rsync-script:

```shell
#!/bin/bash

docker exec drupal-container drush --ansi core:rsync $@
```

**Describe alternatives you've considered**

Bypassing whole Drush and sync files other way.
