### ISSUE TITLE
boolean options not loading from config file

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#6134]
**Describe the bug**
Boolean options defined in drush/drush.yml aren't used when running sql-dump.

**To Reproduce**
drush.yml:

```
command:
  sql:
    dump:
      options:
        gzip: true
        structure-tables-key: common
sql:
  structure-tables:
    common:
      - cache
      - 'cache_*'
      - 'sessions'
```

Run `drush sql-dump --result-file=auto`.

**Expected behavior**
A gzip file is saved.

**Actual behavior**
A text sql file is caved.

**Workaround**
Pass --gzip at runtime.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.3.0.0
| Drupal version? | 11.0.5
| PHP version     | 8.3.11
| OS?             | Linux (via ddev)
