### ISSUE TITLE
When installing a recipe and providing config actions for system.site, name and mail are replaced by drush.

### ISSUE THREAD

**Issue by AleMadLei** [drush-ops/drush#6171]
**Describe the bug**
Now that Drush supports to install a site from a recipe, config action `simpleConfigUpdate` for `system.site` is getting overriden by `drush si`.

Here's an example recipe file.

recipe.yml
```
name: 'sample base site'
description: 'provides our custom base site.'
type: 'Site'
install:
  - big_pipe
  - block
  - block_content
  - breakpoint
  - ckeditor5
  - config
  - contextual
  - datetime
  - dblog
  - dynamic_page_cache
  - editor
  - entity_reference_revisions
  - field
  - field_ui
  - file
  - filter
  - help
  - image
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - mysql
  - node
  - options
  - page_cache
  - paragraphs
  - path
  - path_alias
  - responsive_image
  - system
  - text
  - token
  - toolbar
  - user
  - views_ui
  - pathauto
  - gin
  - gin_toolbar
  - olivero
config:
  actions:
    system.site:
      simpleConfigUpdate:
        name: 'sample site'
        mail: 'dev@email.com'
        slogan: ''
        page:
          403: ''
          404: ''
          front: /node
        admin_compact_mode: false
        weight_select_max: 100
        default_langcode: en
        mail_notification: null

    system.theme:
      simpleConfigUpdate:
        admin: gin
        default: olivero
```

**To Reproduce**
Using the above recipe file, attempt running `drush si -y RECIPE_NAME`

**Expected behavior**
The site install ends up with the site name `sample site` and site email `dev@email.com`

**Actual behavior**
The site install completes but the site name is `Drush Site-Install` and the email `admin@example.com`

**Workaround**
It seems passing the proper values to `drush si`, `--site-mail` and `--site-name` would "fix this" but it would be preferable if this doesn't get overriden if the recipe already provides a value for this.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.x
| Drupal version? | 11.x
| PHP version     | 8.3
| OS?             | Linux
