### ISSUE TITLE
Error during drush deploy when adding a dependency with a service in drush.services.yml

### ISSUE THREAD

**Issue by apotek** [drush-ops/drush#6174]
**Describe the bug**
This seems to be a variant of:
 - https://github.com/drush-ops/drush/issues/3193
 - https://github.com/drush-ops/drush/issues/3730
 - https://github.com/drush-ops/drush/issues/6174 

The general issue has already been handled by Drupal core and also by Drush by using UpdateKernel. The fixes seem to work when using services in module.services.yml. My issue is that this does not appear to work when adding new services to drush.services.yml. 

The error I get is this:

>          In LegacyServiceInstantiator.php line 282:                                
>                                                                                     
>             You have requested a non-existent parameter "fastly.api".    

**To Reproduce**
1. I added the fastly module and config:export added it to core.extension.yml
2. In my custom module, I added a new Drush command that uses a service from the Fastly module (fastly.api). 
3. In my drush.services.yml, I inject the `fastly.api` service to my drush commands.
4. In my own custom module, I wrote an update hook to enable Fastly so that it would be available during deployment.

Then I attempt to deploy with `drush deploy`.

Drush fails with the error message above. 

**Expected behavior**
I expected Drush to ignore the unavailable services (as update.php does) and run the update hook, making services available so that the rest of the deployment can continue.

**Actual behavior**
Drush errors out and cannot deploy, with the following message:

>            In LegacyServiceInstantiator.php line 282:                                
>                                                                                    
>            You have requested a non-existent parameter "fastly.api".    

**Workaround**
There is no workaround. It appears I will have to create two branches in order to move this to production: One branch that will only enable Fastly, and then a second branch to set up the configuration and add my custom drush commands. This will require two sets of testing and two deployments instead of one.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.5.3.0 
| Drupal version? | 10.3.10      
| PHP version     | 8.2.24
| OS?             | Mac

**Additional information**
1. Fastly was added to the artifact with `composer require drupal/fastly`
2. Fastly provides the following service:

```yml
services:
  fastly.api:
    class: Drupal\fastly\Api
    arguments: ['@config.factory', '%fastly.host%', '@http_client', '@logger.channel.fastly', '@fastly.state', '%fastly.connect_timeout%', '@fastly.services.webhook', '@request_stack', '@fastly.cache_tags.hash', '@messenger']
```

3. My custom drush commands use that service, as so, in my drush.services.yml file:

```yml
services:
  my_module.commands:
    class: Drupal\my_module\Commands\MyModuleCommands
    arguments:
      - '@config.factory'
      - '@fastly.api'
```

4. My update hook in my custom module that allows update.php to execute but not `drush deploy` (and our CI tooling of course uses drush).

```php
/**
 * Install Fastly module so its services are available to drush.
 */
function my_module_update_9031() {
  \Drupal::service("module_installer")->install(['fastly']);
}
```
