### ISSUE TITLE
Generating subtheme creates incorrect regions

### ISSUE THREAD

**Issue by lostcarpark** [drush-ops/drush#6299]
**Describe the bug**
Generating a new subtheme with `drush generate theme`, and specifying a base theme, seems to generate a default list of regions in the `.info.yml` file. It should copy the base theme's regions.

**To Reproduce**
I ran `ddev drush generate theme`.
I gave the theme name, and selected my base theme.

**Expected behavior**
Theme would generate with regions matching base theme.
In my case this should have been:
```
regions:
  header_first: Header first (logo)
  header_second: Header second (center)
  header_third: Header third (right)
  highlighted: Highlighted
  content: Content
  fixed_middle_right: Fixed middle right (local actions tabs)
  fixed_bottom_right: Fixed bottom right (messages)
  footer_top: Footer top
  footer_left: Footer left
  footer_right: Footer right
  footer_bottom: Footer bottom
```

**Actual behavior**
Generated region list was:
```
regions:
  header: 'Header'
  primary_menu: 'Primary menu'
  secondary_menu: 'Secondary menu'
  page_top: 'Page top'
  page_bottom: 'Page bottom'
  featured: 'Featured'
  breadcrumb: 'Breadcrumb'
  content: 'Content'
  sidebar_first: 'Sidebar first'
  sidebar_second: 'Sidebar second'
  footer: 'Footer'
```

**Workaround**
Workaround was to manually copy the regions from the base theme and overwrite the generated list.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.6.0.0
| Drupal version? | 11.2.0
| PHP version     | 8.3
| OS?             | Linux

**Additional information**
I created a subtheme, then enabled it and made it default, then realised nothing was in the correct region, so I copied the regions from the base theme. This caused all the blocks to be disabled, and I had to manually move them to the right regions and enable them. For a novice user creating a subtheme, this would be really offputting.
